/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.29
 * Generated at: 2014-01-07 11:04:04 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class rentDetail_005flist_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=Cp1252");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=Cp1252\"/>\n");
      out.write("<title></title>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("<div id=\"container\">\n");
      out.write("<form>\n");
      out.write("<h1>Rent Detail List</h1><br/>\n");
      out.write("Rent id:<input type=\"text\" name=\"title\"><br/>\n");
      out.write("Book id:<input type=\"text\" name=\"code\"><br/>\n");
      out.write("Quantity:<input type=\"text\" name=\"quantity\"><br/>\n");
      out.write("<input type=\"submit\" value=\"search\">\n");
      out.write("</form>\n");
      out.write("\n");
      out.write("<div id=\"lower\">\n");
      out.write("\n");
      out.write("\n");
      out.write("<a href=\"http://localhost:8080/PerpusLucky/rentdetail/select.do\">Display rent detail record</a>\n");
      out.write("<a href=\"http://localhost:8080/PerpusLucky/rentdetail/add.do\">Add rent detail record</a>\n");
      out.write("<a href=\"http://localhost:8080/PerpusLucky/rentdetail/remove.do\">Remove rent detail record</a>\n");
      out.write("<a href=\"http://localhost:8080/PerpusLucky/rentdetail/update.do\">Update rent detail record</a>\n");
      out.write("\n");
      out.write("<table border=\"1\" style=\"background-color:yellow;border:3px;width:100%;border-collapse:collapse;align:center;\">\n");
      out.write("<tr style=\"background-color:orange;color:white;\">\n");
      out.write("<th style=\"padding:3px;\">No</th>\n");
      out.write("<th style=\"padding:3px;\">Book Name</th>\n");
      out.write("<th style=\"padding:3px;\">Book Code</th>\n");
      out.write("<th style=\"padding:3px;\">Quantity</th>\n");
      out.write("<th style=\"padding:3px;\">Edit</th>\n");
      out.write("<th style=\"padding:3px;\">Detail</th>\n");
      out.write("<th style=\"padding:3px;\">Delete</th>\n");
      out.write("</tr>\n");
      out.write("\n");
      out.write("<tr>\n");
      out.write("<td style=\"padding:3px;\">1</th>\n");
      out.write("<td style=\"padding:3px;\">Name</th>\n");
      out.write("<td style=\"padding:3px;\">Code</th>\n");
      out.write("<td style=\"padding:3px;\">35</th>\n");
      out.write("<td style=\"padding:3px;\"><a href=\"http://localhost:8080/PerpusLucky/rentdetail/update.do\">Edit</a></th>\n");
      out.write("<td style=\"padding:3px;\"><a href=\"http://localhost:8080/PerpusLucky/rentdetail/select.do\">Detail</a></th>\n");
      out.write("<td style=\"padding:3px;\"><a href=\"http://localhost:8080/PerpusLucky/rentdetail/remove.do\">Delete</a></th>\n");
      out.write("</tr>\n");
      out.write("\n");
      out.write("</table>\n");
      out.write("\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("</div>\n");
      out.write("</body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
